UPDATE skills set image = '/static/image/skills/python.svg' WHERE id = 1;
UPDATE skills set image = '/static/image/skills/java.svg' WHERE id = 2;
UPDATE skills set image = '/static/image/skills/html-5.svg' WHERE id = 3;
UPDATE skills set image = '/static/image/skills/css-3.svg' WHERE id = 4;
UPDATE skills set image = '/static/image/skills/sass.svg' WHERE id = 5;
UPDATE skills set image = '/static/image/skills/javascript.svg' WHERE id = 6;
UPDATE skills set image = '/static/image/skills/jquery.svg' WHERE id = 7;
UPDATE skills set image = '/static/image/skills/nodejs.svg' WHERE id = 8;
UPDATE skills set image = '/static/image/skills/spring.svg' WHERE id = 9;
UPDATE skills set image = '/static/image/skills/ruby.svg' WHERE id = 10;
UPDATE skills set image = '/static/image/skills/rails.svg' WHERE id = 11;
UPDATE skills set image = '/static/image/skills/django.svg' WHERE id = 12;
UPDATE skills set image = '/static/image/skills/php.svg' WHERE id = 13;
UPDATE skills set image = '/static/image/skills/noimage.png' WHERE id = 14;
UPDATE skills set image = '/static/image/skills/noimage.png' WHERE id = 15;
UPDATE skills set image = '/static/image/skills/oracle.svg' WHERE id = 16;
UPDATE skills set image = '/static/image/skills/mysql.svg' WHERE id = 17;
UPDATE skills set image = '/static/image/skills/noimage.png' WHERE id = 18;
UPDATE skills set image = '/static/image/skills/git.svg' WHERE id = 19;
UPDATE skills set image = '/static/image/skills/subversion.svg' WHERE id = 20;
UPDATE skills set image = '/static/image/skills/java.svg' WHERE id = 21;
UPDATE skills set image = '/static/image/skills/slack-icon.svg' WHERE id = 22;

UPDATE portfolios set top_image = '/static/image/products/portfolio.png', image = '/static/image/products/portfolio.png' WHERE id = 1;
UPDATE portfolios set top_image = '/static/image/products/moneybot.png', image = '/static/image/products/moneybot.png' WHERE id = 2;
UPDATE portfolios set top_image = '/static/image/products/muchohalf.png', image = '/static/image/products/muchohalf.png' WHERE id = 3;